#!/bin/bash

# Written by Jared Weiss to attempt to get a local network stream working.
# Currently suffers from terrible jitter and dropped frames. Think it may just
# be my terrible internet connection.

fps=12
echo stream.sh: fps: $fps
height=600
echo stream.sh: height: $height
width=400
echo stream.sh: width: $width

raspivid -o - -t 0 -n -w $width -h $height -fps $fps | cvlc -vvv stream:///dev/stdin --sout '#rtp{sdp=rtsp://:8080/}' :demux=h264 --h264-fps=$fps
